{
    errdata = "\27[01m\27[K14_class_move/main.cpp:\27[m\27[K In function ‘\27[01m\27[Kint\27[01;32m\27[K main\27[m\27[K(int, char**)\27[m\27[K’:\
\27[01m\27[K14_class_move/main.cpp:70:10:\27[m\27[K \27[01;35m\27[Kwarning: \27[m\27[Kmoving ‘\27[01m\27[Kfib0\27[m\27[K’ of type ‘\27[01m\27[KDynFibonacci\27[m\27[K’ to itself [\27[01;35m\27[K-Wself-move\27[m\27[K]\
   70 |     \27[01;35m\27[Kfib0 = std::move(fib0)\27[m\27[K;\
      |     \27[01;35m\27[K~~~~~^~~~~~~~~~~~~~~~~\27[m\27[K\
\27[01m\27[K14_class_move/main.cpp:70:10:\27[m\27[K \27[01;36m\27[Knote: \27[m\27[Kremove ‘\27[01m\27[Kstd::move\27[m\27[K’ call\
"
}